### ISSUE TITLE
Multiple READMEs

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#103]
I understand that there needs to be both an rst and md version of the README, but it seems that another version (without any extension) has appeared. Is this for PyPI? And if so, why do we have the rst version then?

**Comment by kdere** [comment]
PyPI looks for a README or README.txt that is actually an rst file, although, I should check again.  We could always create a new README in rst format from the .md for a release.

**Comment by wtbarnes** [comment]
Ah ok. So then maybe best to just keep the (extensionless) `README` and remove `README.rst`

**Comment by kdere** [comment]
I have removed the README.rst from my version and it will be propagated into the upstream version on my next PR
