### ISSUE TITLE
Ambiguity in multiple continuum methods

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#104]
In the `continuum` class, there are two methods related to the free-bound continuum: 
* [`freeBoundEmiss`](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/core/Continuum.py#L87)
* [`freeBound`](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/core/Continuum.py#L290)
and two methods related to the free-free continuum:
* [`freeFreeEmiss`](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/core/Continuum.py#L732)
*[`freeFree`](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/core/Continuum.py#L657)

In the free-bound case, according to the documentation, `freeBound` calculates the rate coefficient (returned in the `FreeBound` dictionary) while `freeBoundEmiss` calculates the continuum emissivity. Is the only difference between these two that one (the rate coefficient from `freeBound`) is multiplied by the abundance and the ionization equilibrium? If so, why can't these just be the same method with a kwarg to include (or not include) these extra quantities?

In the free-free case, it seems that both `freeFree` and `freeFreeEmiss` populate the dictionary `FreeFree` with the same key names, but with different results. Presumably this is the same case as in free-bound: `freeFree` includes the ionization equilibrium while `freeFreeEmiss` does not. Either they should populate different dictionaries or they should be combined into a single method with a kwarg to include ionization equilbrium and/or abundance or not.

**Comment by kdere** [comment]
I think this was an attempt to mimic the CHIANTI way of doing things but I did it very early on.  The 2 Emiss methods are probably only rarely used and should just populate different dictionaries.  I think the best way to resolve this is to create different dictionaries.  It is easy to recover from the change if we do it this way.

**Comment by wtbarnes** [comment]
Ok so then it there would only be two methods:
* `freeFree`
* `freeBound`
and depending on the kwargs, each would populate one of two dictionaries per method:
* `FreeFreeEmiss` or `FreeFree`
* `FreeBoundEmiss` or `FreeBound`

Another option would just be to add these as different keys to the same dictionary. This might be a bit cleaner. Or, alternatively, just let the user multiply by the ionization equilibrium and/or abundance since this information is already available to them. So then each method only returns one dictionary with one piece of information.

**Comment by kdere** [comment]
I think it is best if ChiantiPy takes care of multiplying by the abundance and ionization equilibrium.  Otherwise, it causes the user a certain amount of dog-work that can be easily avoided

**Comment by wtbarnes** [comment]
Ok that seems to make sense.

So just to make sure I understand this correctly:
* the methods suffixed with "Loss" include ionization equilibrium and abundance but **not** emission measure
* the methods suffixed with "Emiss"  do **not** include the ionization equilibrium or the abundance or the emission measure
* the methods without any suffix include the ionization equilibrium, abundance, and emission measure

Is this correct?

**Comment by kdere** [comment]
right now we have the methods  freeFree, freeFreeEmiss, freeFreeLoss, an so on for freeBound

freeFreeEmiss calculates the free-free spectrum a for a given ion --it does not include the abundance, ionization equilibrium or emission measure.
freeFree calcuates the spectrum for a give ion and includes the abundance and ionization equilibrium and emission measure as specified - the emission measure is specified in the continuum __init__ method.
freeFreeLoss calcuates the energy loss of a given ion and includes the abundance, ionization equilibrium BUT NOT the emission measure.  It probably should include the EM if is specified.

A lot of editing needs to be done in the Continuum class, for example many of the defaults or 0 (zero) for False or None and they should be explicity be set to that and then check how things propagate through the code.

Does this make sense?

**Comment by wtbarnes** [comment]
Ok I see now. 

So then how do these methods compare with the output of the CHIANTI IDL continuum methods? Presumably, if one was to add the output of `continuum.freeFree` (`continuum.freeBound`) for all ions, you should get the same answer as that produced by `FREEFREE` (`FREEBOUND`)?

**Comment by kdere** [comment]
ChiantiPy  is not meant to be a duplicate of CHIANTI.  Another issue is that I have not implemented the relativistic free-free cross-sections of Itoh so the free-free is the non-relativistic result based on Sutherland.

**Comment by wtbarnes** [comment]
Ok. Just trying to understand the differences between how IDL and ChiantiPy do the continuum calculation. 

I think some of my confusion stems from the fact that the docstrings for a lot of the continuum methods are a bit confusing. It looks like I was last to edit these so I seem to only have myself to blame! This is all a bit more clear now so I will try to clean those up a bit and clarify some of the confusion soon.

**Comment by wtbarnes** [comment]
Closed by #114
