### ISSUE TITLE
RTD builds timeout

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#107]
For the last day or so, all of our Read the Docs builds have failed because of a timeout at ~900 s. Typically, the entire build should only take about ~400 s. 

Each of the build steps seems to be taking ~10x as long as it should compared to past successful builds. [See build logs here](http://readthedocs.org/projects/chiantipy/builds/). 

I don't believe any part of the docs has changed in the last few commits so its possible this is due to an upstream change in one of the packages we install on RTD.

**Comment by kdere** [comment]
I have noticed the time out.  I did a commit that deleted the ion.populateNew method but they have been failing before that.

**Comment by wtbarnes** [comment]
I think this timeout is due to the SciPy docs being down. When our docs are built, it tries to connect to the docs of a few different projects so that it can link to relevant objects/functions/data types in those projects. 

Because SciPy is down, it tries for a long time to connect, times out, and then subsequently caused the RTD build to timeout.

**Comment by wtbarnes** [comment]
Scipy docs are back up and ChiantiPy docs are building successfully.
