### ISSUE TITLE
Implement PEP8-compliant style

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#115]
[PEP8](https://www.python.org/dev/peps/pep-0008/) is the default style-guide for Python code. Recently SunPy has made a push to enforce PEP8 conventions in all PRs, with the eventual goal of having the whole codebase PEP8-compliant. 

As ChiantiPy attracts more users and developers, we should make an effort to enforce consistent styling across the whole codebase. PEP8 is the standard so it makes sense to adopt this style. Other scientific packages (e.g. numpy, scipy, astropy) also adhere to PEP8. This will help to improve readability as well as usability.

This is not a high-priority issue, but it may be a good idea to try to implement an agreed upon style-guide as new PRs come in. That way, the main work will be in fixing the styling of older code.

**Comment by kdere** [comment]
I will see if there is a way to implement a PEP8 checker in my IDE.  I think some have it.

**Comment by Cadair** [comment]
@kdere many integrate with something like flake8. What IDE are you using?

**Comment by kdere** [comment]
i am using the Eric IDE.  I don't immediately seen a plugin for flake but flake8 is available as a command-line too.

**Comment by Cadair** [comment]
I did not know that IDE existed, cool! The homepage for it claims it has automatic PEP 8 checking!

**Comment by wtbarnes** [comment]
Besides the usual PEP8 fixes (line lengths, spaces after commas, etc.), we should also think about changing the class, function, and variable naming convention in ChiantiPy. Roughly, this means making class names use the "CapWords" convention and letting function and variables names use lowercase with words separated by underscores.

**Comment by wtbarnes** [comment]
There's also the [pep8speaks](https://pep8speaks.com/) bot for automatically linting PRs.

**Comment by kdere** [comment]
I could not figure out how to do PEP8 checking in eric but here is the email I got from Detlev Offenbach

Hello Ken,

the code style checker performs checks according to PEP8 and many others 
(codes starting with E and W are mostly PEP8 related). PEP257 is dealing with 
source code documentation style. The included checker has two styles, 
documentation iaw. PEP257 and the eric docu style, which is derived from it.

The summary is, you are not missing anything.

Regards,
Detlev

Am Freitag, 7. April 2017, 11:24:38 CEST schrieb Ken Dere:
> Hi,
>
> this is not really bug but could not find the address for the mailing list
>
> I am trying to make my code more compatible with the PEP8 standards.
>
> If I go to project/show code style it only give me the option for PEP257
>
> the PluginCodeStyleChecker seems to be installed
>
> I guess I am missing something
>
> thanks,
>
> Ken

**Comment by wtbarnes** [comment]
Theres also the [pep8](https://pypi.python.org/pypi/pep8) command line tool. A bit less convenient, but you could just run that before each commit. 

Between that and the pep8speaks bot, that would probably be more than sufficient.
