### ISSUE TITLE
Create a wiki

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#119]
We should consider creating a wiki for ChiantiPy. This would be a good place to list more long term goals for the package, e.g. becoming a Sunpy-affiliated package, integrating Astropy units, migrating the old SVN repo. Things like this are not necessarily issues (like bugs or feature requests) and might be better served by being listed as "Long term projects" or something like that.

[This can all be done inside the main GitHub page.](https://help.github.com/articles/about-github-wikis/). By default, the wiki can only be edited by owners and collaborators, but can be made publicly editable. The latter is probably easiest.

**Comment by kdere** [comment]
Sounds good.  I would rather not make it publicly editable as there is the possibility of all kinds of things.  Collaborators are fine although I don't know what that category consists of.  I should look into it

**Comment by wtbarnes** [comment]
I think if you gave the 'Members' team access to the ChiantiPy repo, then anyone in that team would be able to edit the wiki...though I'm not 100% sure about that...

Also, I believe the SunPy wiki is publicly editable and I don't think they've ever had any issues.

**Comment by kdere** [comment]
I started a wiki.  See if you can edit it.  Otherwise I will have to see about privileges

**Comment by wtbarnes** [comment]
I don't seem to be able to make edits

**Comment by ehsteve** [comment]
@kdere if you want to share admin responsibilities you can either give @wtbarnes or myself access privileges and we will would be able to take care of some of these issues for you.

**Comment by kdere** [comment]
I think that @wtbarnes is most familiar with what is going one.  It looks like if I go to chianti-atomic and change his privilege to have access to the whole site is what I should do.  Right?

**Comment by wtbarnes** [comment]
I believe that is correct. It seems like there should be some level between 'Owner' (you, @kdere) and 'Maintainer' (me currently) where I can merge pull requests, restart Travis builds, edit the Wiki, etc., but not create or delete repositories, change the organization name, etc. I don't have much experience in setting up teams/permissions groups on GitHub, but @ehsteve  and @Cadair probably do.

**Comment by kdere** [comment]
@ehsteve, @Cadair do you have any idea about how to go about this, or if it can even be done

**Comment by Cadair** [comment]
What exactly are you trying to achieve?

**Comment by Cadair** [comment]
These are the available permission levels: https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by kdere** [comment]
at the minimum, I would like @wtbarnes to be able to edit the wiki.  Another level up would be to allow him to do a PR commit.

**Comment by Cadair** [comment]
I would recommend you just make the wiki globally editable, then you only have to be logged into to GitHub to be able to edit.
I think otherwise only people with merge rights will be able to edit.

In the sunpy organisation we basically have a team per permission level and add people to the teams when we want to give the rights to things.

**Comment by kdere** [comment]
I think the wiki is globally editable now.  We will have to sort out the other permissions

**Comment by wtbarnes** [comment]
Yes I can edit the wiki now so that is good. 

I would suggest that, at the organization level then, I be given "Write" permissions (as they are listed on the link @Cadair posted) to ChiantiPy. This would let me help merge PRs, review submissions, ask for changes, close and assign labels to issues, etc.

Looking at the existing Teams in the chianti-atomic organization, it seems that the Python developers team could just be given write permissions (if they don't have them already) and I could join this team.

**Comment by kdere** [comment]
there are 2 maintainers @wtbarnes and myself who have write privileges.  There are 3 python developers, @wtbarnes , @ehsteve  and myself who have write privileges.  Let me know if there are problems with this

**Comment by wtbarnes** [comment]
This sounds good to me. Looking at a few issues not opened by me and the open PR, I seem to have write permissions. Thanks! 

I think this issue can be closed since the wiki has been created and the permissions issues sorted out.

**Comment by wtbarnes** [comment]
One comment: why is there a maintainers group and a python developers group? These both cover only the ChiantiPy repo and grant "Write" access with the only difference being @ehsteve is not included in the former. I would suggest renaming "Python developers"-->"ChiantiPy maintainers" and doing away with "maintainers" just to simplify things. 

As more people contribute to the project, a "ChiantiPy developers" group could be created with "Read" access only.

**Comment by kdere** [comment]
it just happened from lack of experience with the whole thing
