### ISSUE TITLE
Consolidate mspectrum and ipymspectrum

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#128]
These should be consolidated into a single object. Any changes needed for running in an IPython notebook/session should be able to be configured with command line arguments.

**Comment by kdere** [comment]
they can not be consolidated.  You can not use the multiprocessing module in a Jupyter session, last I heard.

**Comment by wtbarnes** [comment]
Hmmm ok. The Jupyter project/notebook has changed substantially in the past few years so it is possible that there is now support for it...

Either way, I would suggest a common interface to mspectrum, or rather spectrum for that matter, such that the user does not have to use a separate module depending on their environment. Instead, this could be specified by a keyword arg or detected automatically.

**Comment by kdere** [comment]
I would not give this too high a priority on the TODO  list

**Comment by wtbarnes** [comment]
I agree.
