### ISSUE TITLE
Remove `ionWeb` class

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#130]
The [`ionWeb`](https://github.com/chianti-atomic/ChiantiPy/blob/master/ChiantiPy/core/Ion.py#L3211) appears to be unused and outdated. I think it can be safely removed.

**Comment by kdere** [comment]
ionWeb was used as the basis for serving up ChiantiPy calculations through a wsgi web interface.  It worked well enough but I needed a more responsive server.  It has not changed for a while so I will remove it soon

**Comment by wtbarnes** [comment]
Ok. If there is ever a web interface implemented for CHIANTI/ChiantiPy,  it should probably be in a separate package as well.

**Comment by wtbarnes** [comment]
Closed by #132
