### ISSUE TITLE
0.7.1 release

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#134]
The fixes recently introduced in the `Continuum` module are fairly substantial. We should probably think about doing a release soon so that these changes can propagate to PyPI. It would also be nice to make ChiantiPy available on Anaconda via `conda-forge` though see discussion in #76

**Comment by kdere** [comment]
A 7.1 release sounds like a good idea.  For v7.0, I just created a release through github but was unsure about whether I should also create a tag, or if this was done automatically , or if it did not mattter.

about #76 , I will bring this up at out CHIANTI skype next week

**Comment by wtbarnes** [comment]
Great! Yes I think we should standardize and automate the release procedure as much as possible. @Cadair has provided [a nice checklist that they use for SunPy](https://gist.github.com/Cadair/224b2d044ee45e80b589). This will make releases easier and allow people to get updates quickly through pip.

EDIT: updated version of SunPy checklist is [here](https://gist.github.com/nabobalis/5c2056875a2f3a6ae1f853700bea04d0)

Also, we could still create a conda-forge recipe for ChiantiPy without the database being repackaged. It would just mean that after installing ChiantiPy, users would still need to  grab the database tarball. For just using ChiantiPy, this isn't too much of a problem, but could be an issue for packages that might want to add ChiantiPy as a dependency (e.g. SunPy).

**Comment by kdere** [comment]
there us a problem in the free-bound calculation.  It is inside a try: statement so any problems are not noticed.
also, all of the methods start with _calculate_ and this is a long word to start with and not very helpful way to find you way around.  it would be better to start with ff or fb and tag a _calc_ on at the end.  However, since just about all methods calculate something, there is no reason to just drop it.

**Comment by wtbarnes** [comment]
What is the issue with the free-bound calculation specifically? If it is a bug, a new issue should be created. Are you referring to the issue raised on the mailing list? I agree this should be dealt with before a 0.7.1 release.

Yes I struggled with the naming convention a little bit. I appended the "calculate" to the methods to distinguish them from the attributes that they return the result to. I would be fine with changes to these method names provided we roughly stick to PEP8 (uppercase classes, lowercase methods and attributes) and use descriptive names.

Most editors and IDEs and stuff like the Jupyter notebook have autocomplete so I don't think long method/class/variable names are really an issue. Also, descriptive names are always better than shortened more ambiguous ones, e.g. freebound as opposed to fb is much more user-friendly, especially for beginners.

**Comment by kdere** [comment]
I think we need to do this one step at a time.  For example, we can do a 0.7.1 release but the Quick-Start guide has to be updated as well.  I am currently having problems creating matplotlib plot in the notebook and the qtconsole -- they just don't show up.

Yes, autocompletion is often available but I would rather start with something more meaningful such as **ff** or **fb** and then hit the tab.

**Comment by kdere** [comment]
we also have to alert the users that the process of going to PEP8 is underway.  Otherwise, they may not understand what is going on.

**Comment by wtbarnes** [comment]
Ok. The note about PEP8 compliance could be included with the release notes and announcement on email lists. As long as the documentation reflects these changes, I doubt people will be too bothered by it.

(Perhaps this should be moved to a separate issue) Ok. Again the problem is conflicts with the attributes used to hold each of the results. One option would just be to move "calculate" (or some other identifier) to the end, e.g. `calculate_free_bound_emission()` becomes `free_bound_emission_calculate()` though this seems a bit awkward. I think the use of full words over abbreviations (ff,fb) is preferable for the sake of clarity.

**Comment by kdere** [comment]
I think that `free_bound_emission_calculate()` is preferable than starting with `calculate.`

**Comment by wtbarnes** [comment]
Ok. I do agree that prepending everything with `calculate` is awkward. I'll move this to a separate issue so that it isn't lost in this thread.

**Comment by kdere** [comment]
I think the next thing to do is the v0.7.1 release, especially that the continuum is much improved.

**Comment by wtbarnes** [comment]
Has #137 been resolved? I thought this was one of the roadblocks to the next release

**Comment by kdere** [comment]
no, it has not been resolved.  I looked at it again and the problem seems to be minor and I will fix that

**Comment by kdere** [comment]
I can fix it by itself but it does not work with mspectrum because mputils is looking for ChiantiPy.core.continuum.  I suspect that the same thing will happen in ipymspectrum

before going on,  we need to think this thing all the way through.

also, I would still like to get rid of the big word **calculate** at the beginning of the methods and put something like just **_calc** at the end
