### ISSUE TITLE
Add the ability to download the chianti database

### ISSUE THREAD

**Issue by ehsteve** [chianti-atomic/ChiantiPy#15]
It would be helpful if there was some function like download_database() which goes out and installs the database in some default but user-configurable directory. Chiantipy should also keep track of what version of the database is has installed (if any) and issue a error if the version is not compatible with a new database file or if no database file is found (and can suggest how to download it).

**Comment by Cadair** [comment]
I know little about Chianti, but would it be worth distributing Chianti as a seperate conda package? This would remove the burden of version monitoring from ChiantiPy. How closely linked are ChaintiPy and the database??

**Comment by kdere** [comment]
Right now there are two ways to get the Chianti database.  Through solarsoft or to download the tarball from chiantidatabase.org

ChiantiPy and the Chianti database are two separate packages.  However, ChiantiPy needs the database.  Also, sometimes the database has changes in certain file structures or other things and a new version is released.  ChiantiPy has to keep up with this.

**Comment by ehsteve** [comment]
So I guess what I am suggesting is that similar capability be provided by ChiantiPy as is provided by solarsoft.

**Comment by Cadair** [comment]
from a conda packaging perspective it would make the most sense to distribute the database as one package and chiantipy as another. For users not using conda it would be good to have a way of downloading the database through python I guess.

**Comment by kdere** [comment]
closing this issue
