### ISSUE TITLE
Restructure package

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#151]
Currently, all of the core parts of the ChiantiPy package are stored in the submodule ChiantiPy.core. However, this extra submodule is really not necessary and creates the need for implicitly importing all modules anytime one is needed, e.g. PR #148 

Furthermore, restructuring the package in this way will allow the docs to be structured a bit more sensibly and we can provide more info in the API docs about individual objects/modules (a la [SunPy docs](http://sunpy.readthedocs.io/en/latest/code_ref/map.html))

I propose moving all of the core objects from the ChiantiPy.core dir to the ChiantiPy dir. So importing the ChiantiPy ion object would look like,
```python
from ChiantiPy import ion
# or
import ChiantiPy.ion
```
without having to import all other modules. It will certainly be faster and I think a bit cleaner.

As @kdere points out in #148, this may create some circular import issues so this may not be as simple as it appears...

**Comment by kdere** [comment]
what I like about the current
`import ChiantiPy.core as ch`
is that you have everything following the ch and only have to guess as the first letter of the class that you want and with tab completion, you get all of the rest.
I am not sure how this cleans up the documentation
and, with todays computers, I don't see importing the whole thing to be much of a burden, although I have no number support this

**Comment by wtbarnes** [comment]
That is true, though you also have tab completion (at least in Jupyter/IPython) when you use the import statements as I showed above. My biggest issue with the current import situation is that when doing `import ChiantiPy.core as ch`,  you're importing every core object, but that is not made explicitly clear.

The import is not exceptionally slow or intensive, but again its the issue of importing a bunch of things at once with explicitly doing so.
