### ISSUE TITLE
calculate_free_free_emission raises IndexError with single temperature input

### ISSUE THREAD

**Issue by ghost** [chianti-atomic/ChiantiPy#155]
As an example, taken from the Quick Start page, this code leads to an IndexError (single process):

```python
temp=2.e+7
dens=1.e+9
wvl = 1. + 0.002*np.arange(4501)
s3 = ch.spectrum(temp, dens, wvl, filter = (chfilters.gaussian,.015),doContinuum=1, em=1.e+27,minAbund=1.e-5,verbose=0)
```

Output:

```python
Traceback (most recent call last):
  File "coronal_spectrum.py", line 11, in <module>
    doContinuum=1, em=1.e+27,minAbund=1.e-4,verbose=0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ChiantiPy-0.7.dev534-py3.6.egg/ChiantiPy/core/Spectrum.py", line 163, in __init__
    FF.calculate_free_free_emission(wavelength)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ChiantiPy-0.7.dev534-py3.6.egg/ChiantiPy/core/Continuum.py", line 176, in calculate_free_free_emission
    gf_itoh = self.itoh_gaunt_factor(wavelength)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ChiantiPy-0.7.dev534-py3.6.egg/ChiantiPy/core/Continuum.py", line 224, in itoh_gaunt_factor
    gf += (itoh_coefficients[i,j]*(t**i))[:,np.newaxis]*(upper_u**j)
IndexError: invalid index to scalar variable.

```

Using arrays for the temperature values works fine. The problem is in line 224 in Continuum.py, were the np.newaxis expression expects the left value to be array-like, whereas a single temperature input leads to an Index Error.

**Comment by wtbarnes** [comment]
Hi Peter,

Thanks for reporting this issue. I think the best way to deal with this is to just make sure any temperature and density that makes it past __init__ is an array and not a single value. So we could still accept single values but just cast them as arrays.

@kdere may have thoughts on how best to handle this as well.

**Comment by kdere** [comment]
It should be possible to use a float or an array for the temperature.  While improving the free-free and free-bound, this got lost along the way.  I will work on getting back to that state.  In the meantime, the v0.7.0 release is available.  I does not have that problem but it also does not have the improved continuum calculations.

**Comment by wtbarnes** [comment]
@Astroprog we've recently merged #157 which fixes the problem where scalar inputs to the continuum methods were raising an IndexError. Try pulling down and installing the latest version (`git pull && python setup.py install`) and seeing if the problem still persists.

**Comment by ghost** [comment]
With the same input as before (with scalar parameters), it now produces a value error:
```python
ValueError                                Traceback (most recent call last)
<ipython-input-2-e123736b312e> in <module>()
      3 wvl = 1. + 0.002*np.arange(4501)
      4 emeas = 1.e+27
----> 5 s3 = ch.spectrum(temp, dens, wvl, filter = (chfilters.gaussian,.015), doContinuum=1, em=emeas,minAbund=1.e-5,verbose=0)

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ChiantiPy-0.7.dev550-py3.6.egg/ChiantiPy/core/Spectrum.py in __init__(self, temperature, eDensity, wavelength, filter, label, elementList, ionList, minAbund, doContinuum, em, keepIons, abundance, verbose, allLines)
    162                 FF = ChiantiPy.core.Continuum(akey, temperature, abundance=abundance, emission_measure=em)
    163                 FF.calculate_free_free_emission(wavelength)
--> 164                 freeFree += FF.free_free_emission
    165 
    166             if 'fb' in self.Todo[akey]:

ValueError: non-broadcastable output operand with shape (4501,) doesn't match the broadcast shape (1,4501)
```
Array-valued parameters however, are still working fine for me

**Comment by kdere** [comment]
I am sorry, but, for now, the continuum module can only be used by itself and not with any of the spectrum routines.  Edits on continuum have been made and the corresponding edits have not been made to the spectrum classes.  The solution will be to make the continuum class work as before.  This will probably happen slowly.  Sorry for the inconvenience.

**Comment by wtbarnes** [comment]
@kdere I think this is a pretty minor issue. In #160 I've just added a commit that calls `squeeze()` (consistent with how the `freeFree` and `freeBound` arrays are created) on the `free_free_emission` and `free_bound_emission` attributes. This seems to fix the problem. 

I've also added some additional tests for `spectrum` that should help to catch these problems in the future.

**Comment by kdere** [comment]
I just pulled the upstream master and that problem remains

**Comment by wtbarnes** [comment]
Hmm that is surprising. It worked on my end and the new spectrum tests, which test both scalar and array inputs, are passing on Travis.

**Comment by kdere** [comment]
The spectrum class now works with a single or a multiple temperature array.  There have also been a number of other changes.
It is now necessary to specify either a elementList, ionList or a minAbund to actually do anything.  Also a doLInes (=1 default) to specify whether the spectral lines are also to be calculated
