### ISSUE TITLE
UsageError: Invalid GUI request 'qt5'

### ISSUE THREAD

**Issue by DanielAndreasen** [chianti-atomic/ChiantiPy#183]
I'm trying to run this tool. After installation and downloading the database I run:
```
import ChiantiPy.core as ch
 found PyQt4 widgets
 using PyQt4 widgets
UsageError: Invalid GUI request 'qt5', valid ones are:['osx', 'qt4', 'glut', 'gtk3', 'pyglet', 'wx', 'none', 'qt', 'gtk', 'tk', None]Error in callback <function post_execute at 0x7fd4f712d848> (for post_execute):
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py in post_execute()
    146 
    147             def post_execute():
--> 148                 if matplotlib.is_interactive():
    149                     draw_all()
    150 

AttributeError: 'NoneType' object has no attribute 'is_interactive'
```
This might not at all be related to Chianti, but I do not have any problems with matplotlib and other packages.

**Comment by kdere** [comment]
your are using the ChiantiPy Qt4 widgets
if matplot lib is using Qt5 then there is a mismatch that might cause this error

assuming you have already
> import matplotlib.pyplot as plt
> plt.rcParams['backend']
gives me:
'Qt4Agg'
if it comes back with Qt5..., then there is a mismatch
my current best guess

**Comment by DanielAndreasen** [comment]
This is my bad. Seems for some reason I was using the system iPython instead of the version I use from anaconda. No problems now, thanks 👍

**Comment by kdere** [comment]
the latest version of IPython only supports Python3.X
you might keep that in mind.
