### ISSUE TITLE
Need to import from source folder after installation

### ISSUE THREAD

**Issue by DanielAndreasen** [chianti-atomic/ChiantiPy#184]
After I succesfully install Chianti (and the dependencies) I am unable to import anything from outside the source folder and get the `ImportError`.

```
>>> import ChiantiPy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-06895db01ac4> in <module>()
----> 1 import ChiantiPy

ImportError: No module named ChiantiPy
```

**Comment by DanielAndreasen** [comment]
This is not true. I was installing with a python from anaconda, but opened up iPython from system. No problems anymore!

**Comment by kdere** [comment]
did you go the to top level ChiantiPy directory and
>  python setup.py install
if so, you should not see this problem

did you just download the ChiantiPy distribution?
if you did the latter, it is necessary to make sure that the ChiantiPy directory is in your PYTHONPATH

**Comment by DanielAndreasen** [comment]
Thanks for the extreme fast reply. But problem is solved.
