### ISSUE TITLE
Cleaning up ionization equilibrium calculation

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#19]
`Ion.ioneq` calculates ionization equilibrium for an entire temperature array. `tools.ionrec.ioneq` calculates ionization equilibrium at a single temperature. Could these be combined into a single class? Perhaps some of the functions themselves could be combined?

**Comment by kdere** [comment]
I looked at ionrec.py yesterday.  It is really just a development project.  I should probably pull it out of the main repository.  Perhaps I could put it in a branch but I have not had much success with branches under svn.  Everything that one would need is in the ioneq class.

**Comment by wtbarnes** [comment]
Ah ok. I was just unsure about why the two were separated. 

I would not suggest creating a separate branch for it unless you are planning to merge it into the master branch at some point. Alternatively, if it is a project that you'd like to keep separate from ChiantiPy, you could create a new repository under the chianti-atomic organization and put it in there.

**Comment by wtbarnes** [comment]
Closing this as `ChiantiPy/tools/ionrec.py` was removed in #24
