### ISSUE TITLE
Make FortranFormat a dependency 

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#20]
Currently, the [FortranFormat](https://pypi.python.org/pypi/fortranformat) module is bundled with ChiantiPy. I think this was because at some point, the package was not Python 3-compatible and so changes had to be made to the package itself. From what I can tell, it is now compatible with Python 3.

In the interest of slimming down ChiantiPy and not having to manually keep up with any updates in the FortranFormat package, FortranFormat could just be added as a dependency.

**Comment by kdere** [comment]
That sounds good.  Let's just wait until I get my fork into shape.

**Comment by kdere** [comment]
I just looked at fortran format.  It is currently at version 0.2.5.  This is what I had to modify to make Python3 compliant so I am a bit confused.

**Comment by wtbarnes** [comment]
Ah ok. I didn't know which version you had originally pulled into the package. It didn't look like the package had been updated in a while so this isn't too surprising.

Do you remember where specifically you made the changes? If python 3 compatibility is still an issue, is there any way we can just wrap the routines that we need rather than having to modify the package itself? This way, we could still add FortranFormat as a dependency without having to bundle it with ChiantiPy.
