### ISSUE TITLE
Array comparison with None should be done with `is` instead of `==`

### ISSUE THREAD

**Issue by ebuchlin** [chianti-atomic/ChiantiPy#206]
Hello,
in [`Spectrum.__init__()`](https://github.com/chianti-atomic/ChiantiPy/blob/f95a818b3eca712e7fb1743e67354c937b305f09/ChiantiPy/core/Spectrum.py#L100), there is a comparison of `em` to `None`, that is done with a `==`. But this fails if `em` is a numpy array: `==` gives a boolean, element-wise, and so produces an other numpy array that cannot be used by `if`. The program crashes with "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()". I think that this line should be `if em is None:`, which is what is advised to do anyway when testing *identity* to `None` (and not *equality*).

A minimal example:
```python
import ChiantiPy
import ChiantiPy.core as ch
import ChiantiPy.tools.filters as chfilters
import numpy as np

print(ChiantiPy.Version)
temperature = np.array([1e6, 2e6])
density = 1e9
wvl = np.linspace(200, 300, num=2001)
em = np.array([1e27 ,1e27])
s = ch.spectrum(temperature, density, wvl, filter = (chfilters.gaussian,.2), em=em, doContinuum=0, minAbund=1.e-5)
```
produces
```python
ValueError                                Traceback (most recent call last)
<ipython-input-7-49299e0b5c2b> in <module>()
----> 1 s = ch.spectrum(temperature, density, wvl, filter = (chfilters.gaussian,.2), em=em, doContinuum=0, minAbund=1.e-5)

~/anaconda3/lib/python3.6/site-packages/ChiantiPy-0.7.dev763-py3.6.egg/ChiantiPy/core/Spectrum.py in __init__(self, temperature, eDensity, wavelength, filter, label, elementList, ionList, minAbund, doLines, doContinuum, em, keepIons, abundance, verbose, allLines)
     98         self.Wavelength = wavelength
     99         #
--> 100         if em == None:
    101             em = np.ones(self.NTempDen, 'float64')
    102             ylabel = r'erg cm$^{-2}$ s$^{-1}$ sr$^{-1} \AA^{-1}$ ($\int\,$ N$_e\,$N$_H\,$d${\it l}$)$^{-1}$'

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by kdere** [comment]
thanks for pointing this out.  There are probably other places where this is happening.  Will look into it

**Comment by Raahul-Singh** [comment]
Hi, Is this still open?

**Comment by ebuchlin** [comment]
```
git clone https://github.com/chianti-atomic/ChiantiPy.git
grep -r '[!=]= None' ChiantiPy/ | wc -l
```
gives 14, and there are also 10 occurrences `[!=]= type(None)`. So I guess yes (unless this has been solved somewhere else), but it should be easy to solve.

**Comment by Raahul-Singh** [comment]
Cool. I'll work on it. Thanks!

**Comment by Raahul-Singh** [comment]
In the earlier PR, I made some errors :sweat_smile:. I have rectified them in the new one.
