### ISSUE TITLE
ken dere's fork

### ISSUE THREAD

**Issue by kdere** [chianti-atomic/ChiantiPy#22]
I did the upstream pull and edited the files that had the conflicts and added them,  Then did a commit.  All went well except it say that my fork is now 1 commit behind the upstream.  
How do I find and fix that?

**Comment by wtbarnes** [comment]
The 1 commit you're behind is the merge of your branch into the main repo. If you just do another `git pull upstream master` and then a `git push origin master`, this should bring your branch even with the upstream master.

**Comment by wtbarnes** [comment]
To avoid many conflicts like this in the future, I would recommend doing a `git pull upstream master` periodically, i.e. before starting to add some feature. This will ensure that all of our forks are more or less always even with the upstream.

**Comment by kdere** [comment]
OK, that worked.
Thanks for all the advice and help

**Comment by wtbarnes** [comment]
No problem at all. Glad we could get it sorted out. I think this issue can be closed.
