### ISSUE TITLE
Bug in calculating spectrum including Ca and Ni

### ISSUE THREAD

**Issue by AstroBrandt** [chianti-atomic/ChiantiPy#263]
Hello ChiantiPy Developers,

I recently encountered a bug while fiddling with the test problems in the Quick Start. In Jupyter-lab, I calculated the spectrum using ch.spectrum and noticed when I set minAbund = 1e-6 I got very bizarre results (the spectrum had no lines and was instead a series of plateaus). I explicitly included different elements through elementList and found that this happens when Calcium or Nickel are included. I have attached two plots showing spectra calculated with the same temperature and density. The one with the lines (no_ca_ni.png) was calculated by calling:
s = ch.spectrum(temp, dens, wvl, doContinuum=1, elementList=['h', 'he', 'c', 'o', 'n', 'ne', 'si', 'mg', 's', 'fe', 'na', 'al', 'ar'], abundance='proto_solar_2009_lodders', verbose=0)

The one with the very bizarre structure  (with_ca.png) (it seems to be something in the free-bound calculation) was calculated by calling:
s = ch.spectrum(temp, dens, wvl, doContinuum=1, elementList=['h', 'he', 'c', 'o', 'n', 'ne', 'si', 'mg', 's', 'fe', 'na', 'al', 'ar', 'ca'], abundance='proto_solar_2009_lodders', verbose=0)

The density is 1e12 and temperature is 8e6. However, I see the same results when I use the values in the quick start and difference abundances.

I have been using ChiantiPy version 0.8.7 with a new download of the Chianti database.

Thank you,
Brandt
![no_ca_ni](https://user-images.githubusercontent.com/9288253/67009442-ed41bd00-f0eb-11e9-9a27-9c2276caee2b.png)
![with_ca](https://user-images.githubusercontent.com/9288253/67009443-edda5380-f0eb-11e9-88a3-0562bfc8b0bf.png)

**Comment by kdere** [comment]
Glad you are giving ChiantiPy a try.  I am looking into this but the first thing I notice is that your wavelength scale is in keV.  The use of keV for wavelength/energy has been tested but definitely as much as with Angstroms.  Doesn't mean that is the problem but I will start with Angstroms

**Comment by AstroBrandt** [comment]
Hi,

I apologize, the calculation is done in Angstroms (as in the Quick Start, I just calculate down to 0.2 Angstroms), I just transform the wavelength axis to energy for use in plotting (the spectrum is still per Angstrom).

Thank you

**Comment by kdere** [comment]
I think I have found the bug.  For the time being, it looks like you can do spectrum calculations if the temperature is an array/list/tuple of at least numbers.  
In the mean time, I fill fix the bug and make a new release.
Thanks for pointing this out.

**Comment by AstroBrandt** [comment]
Thank you for fixing the bug. I will use an array for the time being as suggested.

**Comment by kdere** [comment]
seems I left out the the temperature must have at least **2** values

**Comment by kdere** [comment]
I have created a new release v0.9.0 that should fix the problem.
It is available on github and PyPI

**Comment by AstroBrandt** [comment]
Thank you. I have updated and all appears to be working now!
