### ISSUE TITLE
calling gofnt() when plot argument is False

### ISSUE THREAD

**Issue by hdiamondlowe** [chianti-atomic/ChiantiPy#292]
I am not sure if this is a bug, or just that I want something out of ChiantiPy that others do not, but I notice that when I call gofnt() for a given ion, I get a different result for plot=True than for plot=False.

For instance, building on the example of fe14 in the QuickStart tutorial, if I call

`fe14.gofnt(wvlRange=[200, 210], top=10, plot=True)`

and I select every line in the GUI, I get

`In [214]: fe14.Gofnt['gofnt']` 
`Out[214: array([0.00000000e+00, 0.00000000e+00, 5.45812377e-31, 1.75900934e-32,        0.00000000e+00])` 
(I made a very short temperature range for ease of printing). 

But if I call 

`fe14.gofnt(wvlRange=[200, 210], top=10, plot=False)`

then I get 

`In [216]: fe14.Gofnt['gofnt']`                                                                        
`Out[216]: array([0.00000000e+00, 0.00000000e+00, 3.34408305e-32, 1.45116257e-33, 0.00000000e+00])`

What I have figured out is that when plotting is false, ChiantiPy just takes the highest intensity line for which to calculate Gn(T). Without the plotting GUI I do not see how to tell ChiantiPy that I actually want the summed Gn(T) for the top 10 lines in the specified wavelength range. To do so I have modified the` Ion.py` code slightly and it seems to work (see below), but I am posting here in case others might want to use the gofnt() function like I do.

My quick fix around line 2929 in `Ion.py`:
```
g_line = topLines   #[gline_idx]#  [0]
gofnt = np.zeros(ngofnt,np.float64)
#if plot:
for aline in g_line:
    gofnt += gAbund*gIoneq*emiss[aline].squeeze()
#else:
#    gofnt += gAbund*gIoneq*emiss[g_line].squeeze()
```

**Comment by kdere** [comment]
Hi,

thanks for pointing this out, I will take a look

Ken

On 11/7/20 9:00 AM, Hannah Diamond-Lowe wrote:
>
> I am not sure if this is a bug, or just that I want something out of 
> ChiantiPy that others do not, but I notice that when I call gofnt() 
> for a given ion, I get a different result for plot=True than for 
> plot=False.
>
> For instance, building on the example of fe14 in the QuickStart 
> tutorial, if I call
>
> |fe14.gofnt(wvlRange=[200, 210], top=10, plot=True)|
>
> and I select every line in the GUI, I get
>
> |In [214]: fe14.Gofnt['gofnt']|
> |Out[214: array([0.00000000e+00, 0.00000000e+00, 5.45812377e-31, 
> 1.75900934e-32, 0.00000000e+00])|
> (I made a very short temperature range for ease of printing).
>
> But if I call
>
> |fe14.gofnt(wvlRange=[200, 210], top=10, plot=False)|
>
> then I get
>
> |In [216]: fe14.Gofnt['gofnt']|
> |Out[216]: array([0.00000000e+00, 0.00000000e+00, 3.34408305e-32, 
> 1.45116257e-33, 0.00000000e+00])|
>
> What I have figured out is that when plotting is false, ChiantiPy just 
> takes the highest intensity line for which to calculate Gn(T). Without 
> the plotting GUI I do not see how to tell ChiantiPy that I actually 
> want the summed Gn(T) for the top 10 lines in the specified wavelength 
> range. To do so I have modified the|Ion.py| code slightly and it seems 
> to work (see below), but I am posting here in case others might want 
> to use the gofnt() function like I do.
>
> My quick fix around line 2929 in |Ion.py|:
>
> |g_line = topLines #[gline_idx]# [0] gofnt = 
> np.zeros(ngofnt,np.float64) #if plot: for aline in g_line: gofnt += 
> gAbund*gIoneq*emiss[aline].squeeze() #else: # gofnt += 
> gAbund*gIoneq*emiss[g_line].squeeze() |
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://secure-web.cisco.com/1vqRwrSuqJTiCGC5LbyJWKeJDxeVpZS6FYg-w2C7D9bYkGJO3s6WhE238OLJdBMSsilHeWN-nMd3xh0BXyX6fUwWKTEtgik0hJH4tRvRbuGu8BapDFV0_Zd2Gx5exMUf6vwbxn_3KBeGRmuvhnnvQf2GQtcK_NT0dCUjllz-Z8Z3GhOh_Wvin5UQd_5qoZ8b8EPVSl0Gd3B6cQc2LB_pv5ED5AxR7AeIlOeCkHvidferjj2slCG9QYuVfWLMlVQTjqtcTPEkVTRotIjn1XlcnMSOSmM-9qqRUfNOXQZWLpTULCO_3JU6gFFYQlVxNtRGdEKKUrfCM0s9RLIrFn966fWGm14EnSsrejhJjVzDcfbW836g1e2_933AA4Z7ZxaXikowbz_75WVlkQkQqIVk8RXoWgotfNuo4j02emHx07CoaJ9LfJBSd84ksTN0Jee59/https%3A%2F%2Fgithub.com%2Fchianti-atomic%2FChiantiPy%2Fissues%2F292>, 
> or unsubscribe 
> <https://secure-web.cisco.com/1Qi-tFFm_jkvBcknuNDN1NYed3J5t6uUTcyrOlHYAu76CU9KW6F6fZIyf1yiSnbGZXCREpPHqsYSH7dARoQVbuyvzZkDrIWbecOIqlFDaoBAB0Oa0w_Liwt_OD1XqBuiET-xlVBK6KXGNFDqGLWPqVPc2HhDy_bQIl_zjkp21MOVktK4krJRo2n7! 
> u6btDuhr0v22kfqT_4cwTFv_2ZWtAmNaSGYoqE9MlPTD01I50OkKbTEV7I9agoWZNLhaSkkEisQTGH_NU2MAiZZxBIGysW7llknxpf-0_CNWW_QSKlFjP7Wg-cpYxtWv5ciJLn_DM1ql7TDkJIBYtkqv6hmIV16CNHPx57dKEE5fdGKrZBXtGD6Tr7zO_BZg77kysJvYgOXqrccve2xXZhogry_tbPz633pwOsX8CIkftXQJsSsaLwAdXTZDVG3ss0DQDc-57/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAFUQVTVYLSRPCY6WYAKMBLSOVHHPANCNFSM4TNVKC5Q>.
>
-- 
Kenneth P. Dere
Research Professor of Solar Physics
Department of Physics and Astronomy
George Mason University
kdere@gmu.edu

**Comment by kdere** [comment]
I believe I have fixed the problem.  I have updated the code on github but have not yet made a new release

**Comment by hdiamondlowe** [comment]
Hi Ken, Thanks for your help!

This has somewhat fixed the issue, but now you have to select lines from a dialog box every time the gofnt() function is called. I basically just want Chianti to calculate Gn(T) for the top ten (or however many) lines in a given wavelength range. I am doing this for a lot of different ions in a lot of different wavelength ranges, so I don't want to have to click through the dialog box every time. Perhaps this is not quite the intended usage of ChiantiPy, but I have gotten the results I want using the hack I wrote earlier.

**Comment by kdere** [comment]
Hi,
If you go to the quick start guide, just below the discussion of gofnt, it discusses that there are other ways to do this where you do not have to do any interactive clicking.  You would just need to find the top lines in some wavelength region.
Ken

**Comment by hdiamondlowe** [comment]
Ah, I see. I was following that example initially but thought that it was easier to use gofnt() with plotting turned off. Apparently that output was not what I thought it was though! I'll circle back to the way I started doing it initially. Thank you for all your help.
