### ISSUE TITLE
mathjax and sphinx for local docs builds

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#30]
@kdere moving this possible mathjax issue to a new thread. Quoting from #16,

> I have been running in circles trying to figure out how to include mathjax (or imgmath) for my local doc builds. I think I have some good leads to follow but if anyone has some good ideas I would appreciate them.

Are equations in restructuredText not showing up when you build the docs with `python setup.py build_sphinx`? For example, I've used the `.. math::` directives in the docstring `ChiantiPy.tools.util.qrp`. 

I don't have any problems when building locally on my machine. `astropy-helpers` actually already includes the needed math extensions as seen [here, lines 150-155](https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/sphinx/conf.py#L150). So I don't think we should have to worry about this...

Which browser are you viewing the docs in? I've had good results with Chrome, Firefox, and Safari.

**Comment by kdere** [comment]
my local sphinx does find the math package but this displays the whole entity as a subscript.  In some places, someone has used :mathrm: which works on rtd but not locally and looks much better.

Actually,the astropy_helpers probably sets me up for imgmath and I have not really tried that yet.

I am using Firefox.

I will try imgmath  next and see what happens.  If that doesn't work, I will try a few more things but I don't expect to be on this forever.

**Comment by wtbarnes** [comment]
Ah ok so the equations just show up as :math:`$\my_latex_equation$` literals? 

I have included a couple of math expressions using :math: (for inline) or .. math:: for separate equations in several docstrings. From what I understand, these are [general Sphinx expressions for typesetting math](http://www.sphinx-doc.org/en/stable/ext/math.html) and should not be dependent on what type of renderer (e.g. mathjax, imgmath, pngmath) you're using.

Yes, astropy-helpers uses imgmath locally. I wonder if there is something wrong with your sphinx installation? Have you tried uninstalling and reinstalling sphinx? What version of sphinx are you using? Perhaps your installed version is missing the math support extension?

I'm also using the `sphinx_rtd_theme` package, though I don't think this should make any difference...

All of this is reminding me too that we should mention somewhere in the docs that if people want to build the docs locally, they will need a few extra dependencies.

**Comment by kdere** [comment]
I think I have it working now
In astropy_helpers/astropy_helpers/sphinx/conf.py, the extension **imgmath** is loaded.  I changed this to **mathjax**
so far so good

**Comment by wtbarnes** [comment]
Hmm strange. Perhaps there is just some issue with imgmath on your local setup? Either way, glad it is working now. 

I would avoid committing any changes you've made to astropy-helpers to the upstream. Since this is a submodule, it would create a bit of a headache if we ever wanted to pull down upstream changes from that repo.

**Comment by kdere** [comment]
I am going to check this one more time -- there are only a few edits involved to the ion class and then push it to the upstream package and see how if the docs are built on RTD.
Let me know if this is not something to do right now.

**Comment by wtbarnes** [comment]
This is PR #31 ? It looks like there are currently conflicts so you might have trouble merging into the upstream.

Looking at the commits, it doesn't look like anything will break RTD. 

We should think about implementing some automatic builds via [Travis CI](https://travis-ci.org/)  as well so that it will be easier to say when PRs break the install at least. Later on tests could be added for better coverage. These also get run when a PR is submitted so if a PR breaks the install/fails a test, you know before the merge happens.

**Comment by kdere** [comment]
Sounds like a good idea.  I followed the link you gave to 'Travis CI' and logged in via github.  Now they want to access my github data.  Is that the way to go?

**Comment by wtbarnes** [comment]
Sounds like this has been resolved in that #33 has been merged. Closing.
