### ISSUE TITLE
Setting up automatic builds/tests with Travis CI

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#32]
(Sorry @kdere to jump to yet another issue thread! Just want to make sure none of these points/discussions gets buried in other threads)

Continuing discussion from #30,

@wtbarnes

> We should think about implementing some automatic builds via Travis CI as well so that it will be easier to say when PRs break the install at least. Later on tests could be added for better coverage. These also get run when a PR is submitted so if a PR breaks the install/fails a test, you know before the merge happens.

@kdere 

> Sounds like a good idea. I followed the link you gave to 'Travis CI' and logged in via github. Now they want to access my github data. Is that the way to go?

**Comment by wtbarnes** [comment]
Yes this will configure a GitHub webhook to allow Travis to know when commits happen on a given repo so it can trigger the appropriate process at each commit, either at every branch or at only those branches that you whitelist.

I've had some experience setting up Travis for a couple of different repos (it is very easy) so I can take a look at this in next day or so. For now, we can just run setup.py to make sure the install is at least not broken. As long as you "switch on" the `chianti-atomic/ChiantiPy` repo, its just a matter of adding a `.travis.yml` file to the repo.

Later on, once some tests get written for different parts of the package, these will be very easy to integrate right into the CI build process so that all tests are run at each commit as well

**Comment by Cadair** [comment]
drive by recommendation, you want this: https://github.com/astropy/ci-helpers

**Comment by kdere** [comment]
I looked at some of the travis web pages and the setup up looked like more than I wanted to take on, such as installing postgres -  well, by itself that is not hard to do.
If it is just as simple as a .travis.yml file, that is fine.
I am in the process of fixing my last pull request.  Hope to finish that this morning - not the only thing on my schedule.  Then I will let you go ahead with travis,  If they don't conflict, please proceed at your leasure.

**Comment by kdere** [comment]
OK, my local code now seems to be up-to-date and I can build the docs and the mathjax stuff shows up OK.
I will next continue with docs for the ion class

**Comment by wtbarnes** [comment]
@kdere Yes, in my experience configuring a Travis build is just a matter of adding the .travis.yml file to the repo. Since this is just a single file in the top level directory, it should not conflict with anything you're working on. 

@Cadair Oh yes I've learned this the hard way. Recently tried to install scipy on Travis with pip...it did not end well. Then I discovered the magic of ci-helpers.

**Comment by kdere** [comment]
I merged the pull request.
I will be on vacation starting next week for 3 weeks  or so.

**Comment by wtbarnes** [comment]
Thanks @kdere. Enjoy your vacation.

Did you enable the build on [travis-ci.org](https://travis-ci.org)? When I go to the [chianti-atomic/ChiantiPy](https://travis-ci.org/chianti-atomic/ChiantiPy) page,  it says it is not an active repository.

**Comment by kdere** [comment]
I think I enabled the build on travis.  Clicked on the build button on ChiantiPy.  Let me know by Tuesday what you think.

**Comment by wtbarnes** [comment]
Everything looks good! Thanks. Closing this issue for now since the initial Travis build has been set up.
