### ISSUE TITLE
Error on running provided jupyter notebooks in the repo

### ISSUE THREAD

**Issue by MadFisa** [chianti-atomic/chiantipy#331]
Hi,

I was trying to run the jupyter notebooks in the repo, I am running into some issues while using it. In particular, trying to run fe_13_demo_make_model notebooks, while running
`box = mdl.maker(specData, wghtFactor = 0.2, ionList=['fe_13'], verbose = True)`
I get an error asking for temperature as an argument. I managed to run it by passing a temperature as an argument. But, on running the line

`box.gofnt(temp, dens, verbose=True)`

I am getting another error, 
"AttributeError: 'maker' object has no attribute 'match'"

Here is the whole error in detail,

```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_30471/2084597862.py in <module>
----> 1 box.gofnt(temp, dens, verbose=True)

~/adnocana/aed/lib/python3.8/site-packages/ChiantiPy/model/Maker.py in gofnt(self, temperature, density, verbose)
    538             print(' density     size:  %5i'%(self.EDensity.size))
    539         ionList = []
--> 540         for iwvl, amatch in enumerate(self.match):
    541             for someIon in amatch['ion']:
    542 #                print 'someIon = ', someIon

AttributeError: 'maker' object has no attribute 'match'
```

I am assuming that there has been changes to code after the notebooks were made. How can I correct this error? 

 I would like fit a spectrum created by chiantiPy to a spectrum data I have and the Maker module seems to have some capabilities in this regard. So far the only place I could find examples for the use of ChiantiPy.Maker module is in those notebooks. Is there other places where I could find example codes?

Edit:
Here is the first line I got the error along with error message:

`box = mdl.maker(specData, wghtFactor = 0.2, ionList=['fe_13'], verbose = True)`

with the error

`TypeError: __init__() missing 1 required positional argument : 'specData'`

I got it to run by editing it as following

`box = mdl.maker(temperature = 1.78e6, specData=specData, wghtFactor = 0.2, ionList=['fe_13'], verbose = True)`

**Comment by kdere** [comment]
Hi,

yes, the model module is under development.

I will try to put together some notebooks for you that work with the latest code.

I should probably also put that in the docs.

regards,
Ken

________________________________
From: MadFisa ***@***.***>
Sent: Thursday, March 10, 2022 1:45 AM
To: chianti-atomic/ChiantiPy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chianti-atomic/ChiantiPy] Error on running provided jupyter notebooks in the repo (Issue #331)


Hi,

I was trying to run the jupyter notebooks in the repo, I am running into some issues while using it. In particular, trying to run fe_13_demo_make_model notebooks, while running
box = mdl.maker(specData, wghtFactor = 0.2, ionList=['fe_13'], verbose = True)
I get an error asking for temperature as an argument. I managed to run it by passing a temperature as an argument. But, on running the line

box.gofnt(temp, dens, verbose=True)

I am getting another error,
"AttributeError: 'maker' object has no attribute 'match'"

Here is the whole error in detail,

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_30471/2084597862.py in <module>
----> 1 box.gofnt(temp, dens, verbose=True)

~/adnocana/aed/lib/python3.8/site-packages/ChiantiPy/model/Maker.py in gofnt(self, temperature, density, verbose)
    538             print(' density     size:  %5i'%(self.EDensity.size))
    539         ionList = []
--> 540         for iwvl, amatch in enumerate(self.match):
    541             for someIon in amatch['ion']:
    542 #                print 'someIon = ', someIon

AttributeError: 'maker' object has no attribute 'match'


I am assuming that there has been changes to code after the notebooks were made. How can I correct this error?

I would like fit a spectrum created by chiantiPy to a spectrum data I have and the Maker module seems to have some capabilities in this regard. So far the only place I could find examples for the use of ChiantiPy.Maker module is in those notebooks. Is there other places where I could find example codes?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1pWzQqyCd6eFq2G1NOCn4yydQo3FRJs7rdYTOKKHGbu3AIO64Jqbt3CNPS58Gkn5SIT6xVrHxSalg4SjT_pgIv6lHfZT3ZXq7hLp6taOQLwCXESMWuZhO4ruOQjd-PsvVxGpFJr19lpMcjqK53odfCVXSopf_IpcZCn5CHFRsDYBnql1q_p7wXVzna9LlFgRIa8kqQLTXI46AfHuIEQtukXsiEb285tZ36x5Fnvf3V9pRpBnYTiiaf7-0-Al-H8BVF0HUmBdCTJHZMX8iIJPhPjYL4IlA3ylUACIXrQauiUXB0cvpUqnZIOz8_89Y1QKsQQmvSqVJoYd_Abug0TCoF4uHBLraBPhAXmylm3iBjRToo7H4eKdgXShzhGzSKV-DJ-g7nvI5ew_kR5LDjtOIPtd8GOgigcOGr4ZFKrzcHnspA6GlGJ_TtScdJKQBH7hM/https%3A%2F%2Fgithub.com%2Fchianti-atomic%2FChiantiPy%2Fissues%2F331>, or unsubscribe<https://secure-web.cisco.com/12pTLGR25bAiwZK2JnM8bvVPhxoMcd9Sel62LHX_Yw_I7vfel3BkpEYGBJBl1DMx9gfLUAN-tKEd25HZohcFJAEcLr1YfCu2kf78dr4acN7OFHt0H30jcgP6A5OgZkBe2BVED-tssCwoRR5VGw-LqA4lNU7Ciu77MJy4t3riBJ2gQjEawT_73S-tcUcGhSlZcCaRCIiD3kCLwmSl0i5FWAE70YBnwdwIsrDRB8EYeROeK8YXeF4v1CrvlzY1ZVy!
%200Vael7ATLacs8jAjkDvvWVySqhrDJT2FFlF_q8GmZm_JSiNl7J2-tibXIMG-lQKXHCIn5Vd3KTfqc-rNNYNdaUga4HGyuEFoP_5Rld4X1dMFtxVYkb6_MC9YcAKDpjsxIsmjGnCs5E0iqRPSq9BwF056E8-d9x7_oqMJwR2_ik-uUqYz6CgvbPmjZJfQ5zIoki/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAFUQVXE7KDFDLEHSPHSNCDU7GLA7ANCNFSM5QLV5Z4A>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckdere%40gmu.edu%7Ca4e9d6acda1e44e24f6a08da026197ac%7C9e857255df574c47a0c00546460380cb%7C0%7C0%7C637824915426208910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=PToxaknJ%2BdjKj06VIlrd%2BzQUOBogZVOG1ifJGp%2F2OdQ%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckdere%40gmu.edu%7Ca4e9d6acda1e44e24f6a08da026197ac%7C9e857255df574c47a0c00546460380cb%7C0%7C0%7C637824915426208910%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lT6hoYDoKWfeM0iiMVDjFNmpMDoQScl6277p45XQh8M%3D&reserved=0>.

**Comment by MadFisa** [comment]
That will be very much appreciated, Thank you. The 'fixed' version of the current notebooks should be sufficient, I believe, unless there are more capabilities added to the module that you would like to show.
 Putting some examples in the docs showing the capabilities of the module will be helpful for anyone looking into it, since current documentation has nearly no info apart from the api documentation.

**Comment by kdere** [comment]
I have updated the README.txt file.

A basic notebook that needs to be run first is  1_fe_13_demo_make_match.ipynb

I am in the process of updating the others
