### ISSUE TITLE
line identifications in spectrum plot

### ISSUE THREAD

**Issue by sengle01** [chianti-atomic/chiantipy#340]
Hello,

I apologize if I've missed it somewhere in the docs - when I'm plotting an emission spectrum that I've calculated with ChiantiPy, is there a built-in command/option for overlaying line identifications on the plot ?

Best,
Scott

**Comment by kdere** [comment]
Hi Scott,
sorry there is not one at present but it would be good to have.
It should not be too difficult to cook up.
regards,
Ken

**Comment by kdere** [comment]
I am working on a new release and will try to include something like that.

**Comment by sengle01** [comment]
Hi Ken,

No worries at all - thank you for the reply and for all the effort. 
Best of luck with the new release; looking forward to seeing everything the team cooks up.

Best,
Scott

**Comment by MadFisa** [comment]
Hi @kdere ,
Is there any update on the feature? Is it implemented yet?

**Comment by kdere** [comment]
Hi,
I have uploaded several new demo notebooks:   bunch_demo.ipynb, spectrum_demo.ipynb and spectrum_dem_2.ipynb.

They had labeling before but it is much improved.  Also, the are notebooks so the code is editable

regards,
Ken

**Comment by MadFisa** [comment]
Hi,
I have tried running the notebooks. In spectrum_demo.ipynb and spectrum_demo2.ipynb the code seems to look for a folder 'em' in CHIANTI directory, which doesnot exist in my version of database. I downloaded the database from https://www.chiantidatabase.org/chianti_download.html and has the version 10.0.1. Where can I get the em files required?

**Comment by kdere** [comment]
Hi,
I will attach the files here.  You will have to create the$XUVTOP./em folder and put them there.
I will ask that we make a new release.

file:///data2/a2git/chdbase/em/active_region_1993_serts_4T.em
file:///data2/a2git/chdbase/em/quiet_sun_1993_serts_4T.em

I am not sure if this works.
Ken

**Comment by kdere** [comment]
6.166e+05      2.000e+09      4.969e+26 
      1.122e+06      2.000e+09      2.089e+27 
      1.862e+06      2.000e+09      7.889e+27 
      3.162e+06      2.000e+09      1.465e+28 
 -1
filename: active_region_1993_serts_4T.em
Brosius, J., Davila, J., Thomas, R., Monsignori-Fossi, B.
1996, ApJS, 106, 143
produced as a part of the 'CHIANTI' atomic database for astrophysical spectroscopy
 K. Dere (GMU) - 2021 June 29

save this in XUVTOP as 'active_region_1993_serts_4T.em'

**Comment by kdere** [comment]
6.166e+05      5.000e+08      1.183e+26 
      1.072e+06      5.000e+08      2.963e+26 
      1.622e+06      5.000e+08      1.073e+27 
      2.344e+06      5.000e+08      6.357e+26 
 -1
filename: quiet_sun_1993_serts_4T.em
Brosius, J., Davila, J., Thomas, R., Monsignori-Fossi, B.
1996, ApJS, 106, 143
produced as a part of the 'CHIANTI' atomic database for astrophysical spectroscopy
 K. Dere (GMU) - 2021 May 20


save this in XUVTOP/em as 'quiet_sun_1993_serts_4T.em

**Comment by kdere** [comment]
simply attached, this time
Ken
________________________________

**Comment by MadFisa** [comment]
I made the file and code seems to run fine. Thank you for your help. Great work as always.

**Comment by kdere** [comment]
There is a new CHIANTI 10.0.2 on the CHIANTI <https://www.chiantidatabase.org/> site with the em files
Ken

________________________________

**Comment by kdere** [comment]
version 0.14.0 has implemented methods that labels lines and spectra with the transitions
