### ISSUE TITLE
Error while using spectrum with elementList only when all the ions are not present in the masterlist

### ISSUE THREAD

**Issue by MadFisa** [chianti-atomic/chiantipy#358]
Here is a simple example that could reproduce the error,

```
import ChiantiPy.core as ch
import numpy as np
conversion = 12.3

energy = np.linspace(0.1,20,1000)
wvl = conversion/energy
temp = 1e7
dens = 1e9
s = ch.spectrum(temp, dens, wvl,verbose=1,abundance= 'unity',elementList=['F'])
```

which gives a keyerror. You can get same error by putting the following elements (all the ones I know) in elements list too: Li, Be, B, F, P, Cl, Ar, K, Ca, Sc, Ti, V, Cr, Mn, Co, Ni, Cu, Zn
I have given the error below
```

KeyError                               Traceback (most recent call last)
File ~/Documents/work/elem_bug_demo.py:10, in <module>
      8 dens = 1e9
      9 # 
KeyError                               Traceback (most recent call last)
File ~/Documents/work/elem_bug_demo.py:10, in <module>
      8 dens = 1e9
      9 # s = ch.mspectrum(temp, dens, wvl,abundance= 'unity',elementList=['Fe'],proc=2)
---> 10 s = ch.spectrum(temp, dens, wvl,verbose=1,abundance= 'unity',elementList=['Fe'])

File ~/anaconda3/envs/aed/lib/python3.9/site-packages/ChiantiPy/core/Spectrum.py:190, in spectrum.__init__(self, temperature, eDensity, wavelength, filter, label, elementList, ionList, minAbund, doLines, doContinuum, em, keepIons, abundance, verbose, allLines)
    188 self.Finished = []
    189 #
--> 190 self.ionGate(elementList = elementList, ionList = ionList, minAbund=minAbund, doLines=doLines, doContinuum=doContinuum, verbose = verbose)
    191 #
    192 for akey in sorted(self.Todo.keys()):

File ~/anaconda3/envs/aed/lib/python3.9/site-packages/ChiantiPy/base/_SpecTrails.py:210, in specTrails.ionGate(self, elementList, ionList, minAbund, doLines, doContinuum, doWvlTest, doIoneqTest, includeDiel, verbose)
    208 toPop = []
    209 for ionS in todo:
--> 210     ioneqTest = (temperature.max() >= ionInfo[ionS]['tmin']) and (temperature.min() <= ionInfo[ionS]['tmax'])
    211     if not ioneqTest:
    212         toPop.append(ionS)

KeyError: 'f_2's = ch.mspectrum(temp, dens, wvl,abundance= 'unity',elementList=['Fe'],proc=2)
---> 10 s = ch.spectrum(temp, dens, wvl,verbose=1,abundance= 'unity',elementList=['Fe'])

File ~/anaconda3/envs/aed/lib/python3.9/site-packages/ChiantiPy/core/Spectrum.py:190, in spectrum.__init__(self, temperature, eDensity, wavelength, filter, label, elementList, ionList, minAbund, doLines, doContinuum, em, keepIons, abundance, verbose, allLines)
    188 self.Finished = []
    189 #
--> 190 self.ionGate(elementList = elementList, ionList = ionList, minAbund=minAbund, doLines=doLines, doContinuum=doContinuum, verbose = verbose)
    191 #
    192 for akey in sorted(self.Todo.keys()):

File ~/anaconda3/envs/aed/lib/python3.9/site-packages/ChiantiPy/base/_SpecTrails.py:210, in specTrails.ionGate(self, elementList, ionList, minAbund, doLines, doContinuum, doWvlTest, doIoneqTest, includeDiel, verbose)
    208 toPop = []
    209 for ionS in todo:
--> 210     ioneqTest = (temperature.max() >= ionInfo[ionS]['tmin']) and (temperature.min() <= ionInfo[ionS]['tmax'])
    211     if not ioneqTest:
    212         toPop.append(ionS)

KeyError: 'f_2'

```

My guess is that when elementlist is passed as an argument, 'todo' dictionary seems to contain entries which doesnot have corresponding data in CHIANTI database. Please note that this issue doesnot seem to arise while using a minAbund or ionList. 

Digging into the code, I see that IonList has a check for checking for whether element is present in CHIANTI,

https://github.com/chianti-atomic/ChiantiPy/blob/061867d1400a48e422209414dd99d0fc91c9b8b3/ChiantiPy/base/_SpecTrails.py#L189-L200

Whereas elementList seems to be missing the check
https://github.com/chianti-atomic/ChiantiPy/blob/061867d1400a48e422209414dd99d0fc91c9b8b3/ChiantiPy/base/_SpecTrails.py#L167-L188

I could be wrong, but my guess is that the problem is this. Please look into it and possible fix.

**Comment by MadFisa** [comment]
It would be very helpful if you could suggest a quick workaround for now.

**Comment by kdere** [comment]
I am working on this at the very moment.  Hope to have a fix soon.

**Comment by kdere** [comment]
I have a revised version of _Spectrails/ionGate

I have tested it but am not quite ready for a new release.  I see that you get your code from conda.  Perhaps I could make a release candidate and conda would probably pick it up if your are interested in testing it.

also, the specification of a user-suppled abundance file should work now
Ken

**Comment by MadFisa** [comment]
Hi,
Thanks for the quick update. I can test out the new code if its availabe. Would it work by doing a simple conda update?

Asif

**Comment by kdere** [comment]
I will try t get a release on github soon and conda should be able to pick it up from there.
Ken

**Comment by MadFisa** [comment]
Thanks!! I will pick it up once it updates.

 Another related bug(?) seems to be that if provided element list has capital letters,( i.e elements=['H','He']), running any of the spectrum classes with elementList=elements, converts the original list to small letters. That is elements become elements=['h','he']. 

While the code runs as expected, this seems like a bit of unexpected behavior to me. Users typically do not expect methods to change the arguments. I couldn't figure out why this was happening, but my guess would be that .lower() in line 168 and 169 _specTrail is affecttig the original list too.

Asif

**Comment by kdere** [comment]
OK, I will change the behavior here as well
Ken
