### ISSUE TITLE
Unexpected behavior when setting minAbund lower than lowest abund

### ISSUE THREAD

**Issue by MadFisa** [chianti-atomic/chiantipy#377]
Hi,
As the title suggests, if minAbund is less than min of abundances, a message appears telling that no ions were selected. The problem seems to be the following lines:

https://github.com/chianti-atomic/ChiantiPy/blob/7605314ef1858825813389ead9675069d53d6d35/ChiantiPy/base/_SpecTrails.py#L44-L46

which sets minAbund to minAbundAll which has type np.float64. This causes the following check to fail
https://github.com/chianti-atomic/ChiantiPy/blob/7605314ef1858825813389ead9675069d53d6d35/ChiantiPy/base/_SpecTrails.py#L184

which results in no ions getting selected.

I believe this can be fixed by changing the problematic line to` minAbund = float(minAbundAll)`.
Hope this helps to fix the bug.

Asif

**Comment by kdere** [comment]
I will check this out
Ken

**Comment by kdere** [comment]
Yes, your fix does the job.  Am working on a new release and this will be in it.
thanks,
Ken

**Comment by MadFisa** [comment]
I believe this was fixed with the latest update (0.14.0). Closing the issue.
