### ISSUE TITLE
How much memory does the mspectrum process consumes?

### ISSUE THREAD

**Issue by Rogerod23** [chianti-atomic/chiantipy#386]
Hello, I am trying to run calculations with the mspectrum method, but I can not find how much memory does this process consumes when is being used, in order to know how much cores I can use without killing the cluster that I am using. Does anyone has this number in hand?

Thank you.

-Rogelio.

**Comment by kdere** [comment]
I do not have a hard number.  On my machine I have 32 GB of memory and can run 6 cores at the same time without memory problems.  There are also applications that show memory and processor usage in near real time.  This would help understand what you are looking at.
regards,
Ken
