### ISSUE TITLE
Clarify emission measure units in the function documentations.

### ISSUE THREAD

**Issue by MadFisa** [chianti-atomic/chiantipy#398]
Hi,

This is a suggestion to improve some of the documentation. It would be great to add the units of emission measure in some of the documentation of classes such as that of spectrum, mspectrum, ipymspectrum etc, as the other units are clearly mentioned ( such as temperature, eDensity, and wavelength). It is in cm^-5 as far as I understand and is not clearly mentioned in the documentation or the quickstart guides as far as I can see. Clearly stating it would help the new users.

Asif

**Comment by kdere** [comment]
I agree.  There should be some sort of introduction in the documentations.

**Comment by kdere** [comment]
This will be in the quick start documentation for the upcoming 0.15.0 release
