### ISSUE TITLE
Possible typo in function's documentation

### ISSUE THREAD

**Issue by AlexandrosKoukras** [chianti-atomic/chiantipy#427]
Hello,

I was looking at the function [intensityRatioInterpolate](https://github.com/chianti-atomic/ChiantiPy/blob/d8518b730ae0599aeeb9fd3f3637b482dc1c6310/ChiantiPy/core/Ion.py#L2881) in chiantipy/chianti/core/Ion.py and it seems to me that in the documentation of the function there is a typo. 
It's written: 

> 'to take a set of **date** and interpolate against the IntensityRatio'

But I believe it meant to be '**data**' and not '**date**'. If that is not the case, can you let me know to what this 'date' refers?
In case that it is indeed a typo, I can make a commit to change it.

Lastly, wouldn't it be better to have a more detail description of the 'data' argument in the description of this function?

**Comment by kdere** [comment]
Yes, date should be data and the docstring could be more informative.  What is supposed to do is take list/array of measured density ratio and return the density corresponding to the intensity ratio
