### ISSUE TITLE
Upload 0.15.1 to PyPI

### ISSUE THREAD

**Issue by tiagopereira** [chianti-atomic/chiantipy#442]
The ChiantiPy version on PyPI and conda-forge is only 0.15.0, which does not work with the current version of the CHIANTI database. Could someone please update the latest release 0.15.1 in those channels? It would make it much more easy to install in multiple systems.

**Comment by kdere** [comment]
The ChiantiPy version on PyPi is 0.15.1  It was uploaded in May.  I think you will need to ask the conda people.

**Comment by kdere** [comment]
The problem that ChiantiPy 0.15.1 was released to correct for was the abundance file

sun_coronal_2021_chianti.abund

if you remove that from the abundance directory, you should be able to run ChiantiPy 0.15.0

hope that helps

**Comment by tiagopereira** [comment]
Thanks for the quick reply. Indeed it is updated on PyPI, just not on conda-forge.
