### ISSUE TITLE
Non-ionization equilibrium?

### ISSUE THREAD

**Issue by Rogerod23** [chianti-atomic/chiantipy#444]
Hi all, I was wondering if anyone has tried to perform non-ionization equilibrium calculations. Particularly to calculate soft X-ray spectra. Is this possible with Chiantipy? 

Bests,

-Rogelio.

**Comment by kdere** [comment]
ChiantiPy is based on knowing the ionization equilibrium.  If you had some way of calculating a non-equilibrium ionization equilibrium, it could be used by ChiantiPy.  
regards,
Ken

**Comment by Rogerod23** [comment]
All right, thank you for your response.

-Rogelio.
