### ISSUE TITLE
Unable to load ioneq

### ISSUE THREAD

**Issue by nawinnova** [chianti-atomic/chiantipy#453]
Hi all,

I have just recently install ChiantiPy (version 0.15.1) and try to follow the quickguide. However, I am unable to load the ion equilibrium data due to some error.

Here is the code I am using.

`import os
import ChiantiPy
import ChiantiPy.core as ch
import numpy as np
import matplotlib.pyplot as plt
import ChiantiPy.tools.data as chdata

os.environ['XUVTOP'] = '/Users/nawinngampoopun/Desktop/CHIANTI/CHIANTI_10.1_database/'

Ocharge = ch.ioneq(8)
Ocharge.load()
`

The return error is AttributeError: module 'ChiantiPy.tools.data' has no attribute 'Defaults'

Is there anyway to solve this issue?

Thank you,
Nawin

**Comment by kdere** [comment]
I am looking into this

Ken

**Comment by kdere** [comment]
Try:

`defaults=chio.defaultsRead()`

and see what  you get for the values of the dict 'defaults'

one should be

`'ioneqfile': 'chianti',`


Ken

**Comment by nawinnova** [comment]
Hi Ken, 

Here is the values of dict

{'abundfile': 'sun_photospheric_2015_scott',
 'ioneqfile': 'chianti',
 'wavelength': 'angstrom',
 'flux': 'energy',
 'gui': True}

**Comment by kdere** [comment]
next thing to try:

`import ChiantiPy.tools.data as chdata`

then chdata.Defaults 

should look like what you got with chio.defaultsRead()

so , theck that.

Ken

**Comment by nawinnova** [comment]
I receive an error this time, similar to the original problem.

import ChiantiPy.tools.data as chdata
----> chdata.Defaults

AttributeError: module 'ChiantiPy.tools.data' has no attribute 'Defaults'

Also, I can add that I am running this in VSCode on macOS, and install ChiantiPy using pip

**Comment by kdere** [comment]
I have never tried VSCode.

can you try this in a Python console, or a jupyter notebook?

Ken

**Comment by kdere** [comment]
does chdata have any attributes such as
Xuvtop
Ip
MasterList
?
Ken

**Comment by nawinnova** [comment]
Hi, I also try to run it using IPython

Here is some results

In [3]: import os

In [4]: os.environ['XUVTOP'] = '/Users/nawinngampoopun/Desktop/CHIANTI/CHIANTI_10.1_database/'

In [5]: import ChiantiPy.tools.data as chdata

In [6]: chdata.Defaults
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 chdata.Defaults

AttributeError: module 'ChiantiPy.tools.data' has no attribute 'Defaults'

In [7]: dir(chdata)
Out[7]: 
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__warningregistry__',
 'chio',
 'glob',
 'klnames',
 'os',
 'traceback',
 'warnings']

**Comment by nawinnova** [comment]
Hi Ken,

I have found the problem now. It maybe because I import the ChiantiPy before define os.environ['XUVTOP']. Now the code is working now after I swap the code and restart the kernel and 

Thank you for your help!
Nawin

**Comment by kdere** [comment]
glad you found your problem

Ken
