### ISSUE TITLE
EMISS_CALC in ChiantiPy

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#47]
In the CHIANTI IDL routines, EMISS_CALC.pro  calculates,

![image](https://cloud.githubusercontent.com/assets/8676141/20122267/1adc0058-a5dc-11e6-9dec-295dd13d8ac6.png)

with units of erg s^-1. The closest function I can find to this is the `emiss` method of the `ion` class which returns a quantity with units ergs cm^-3 s^-1 sr^-1 in the `emiss` field of the Emiss data structure. What exactly is this quantity? I assume that the sr^-1 just comes from the 1/4pi factor. Will dividing by N(X+m) (and multiplying by 4pi) give the same output as EMISS_CALC?

**Comment by kdere** [comment]
in ChiantiPy, the N_j/N is included.  The only difference is that in ChiantiPy, the emissivity is per steradian (1/4 pi).  Multiply it by 4*pi and it should be the same as the IDL result.

**Comment by wtbarnes** [comment]
This seems to contradict [the `emiss` method docstring](http://chiantipy.readthedocs.io/en/latest/api/ChiantiPy.core.ion.html#ChiantiPy.core.ion.emiss) which says that the result in the `emiss` field has units of erg cm^-3 s^-1 sr^-1 so multiplying through by 4pi still gives erg cm^-3 s^-1. So where does the cm^-3 come from?

**Comment by wtbarnes** [comment]
Looking at the source code more closely, it seems that the units listed in the documentation should actually be erg s^-1 sr^-1 (or photons s^-1 sr^-1, depending on the default settings) since `emiss` in this case is just the product between the population (unitless), the A value (s^-1) and the energy factor (erg or photons).

**Comment by kdere** [comment]
You are right.  I will change the doc string and will do some other pushes soon

**Comment by wtbarnes** [comment]
I was planning on doing some work in the `ion` class (a la #48 ) so I can take care of this then also.

**Comment by wtbarnes** [comment]
Fixed by #50
