### ISSUE TITLE
Codebase cleanup

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#48]
There seems to be quite bit of commented out code in ChiantiPy. When version control is not being used, this is of course often necessary to preserve some sort of history. However, now that the codebase has moved to GitHub, I propose deleting these commented out lines as git and GitHub do an excellent job of preserving the history of every line of every file.

This will greatly decrease the total number of lines in ChiantiPy and greatly increase its readability in a few places. I'm more than happy to open a PR to take care of this.

**Comment by kdere** [comment]
You are right again.  I have to clean up ipyMspectrum since there is now a lot of commented out code trying to get it to work again.  I have also made a few changes in the ionization functions as they are returning incorrect values.  I am in the process of buying and IDL(!) license to try to sort this out.

So, let me do this and then do a complete circle through my fork and through the upstream and back and then you should be free to work on this.  thanks!

**Comment by wtbarnes** [comment]
Thanks that sounds great! I'll wait from the Ok from you. 

As an aside, it may be helpful to open a PR against the upstream repo while you're implementing your changes so that others can see what you're currently working on and avoid working on those same files/lines of code.

**Comment by kdere** [comment]
I am done for the time being.  What is a PR?

**Comment by wtbarnes** [comment]
Ah sorry. PR=pull request.

**Comment by kdere** [comment]
I should have figured that out.  I did several PRs and all of the reposes at at the same commit level

**Comment by wtbarnes** [comment]
Ok. I'll open up a PR soon Re: some cleanup of the ion class first.

**Comment by kdere** [comment]
I see a pull request but also your statement that it is not ready.  Let me know when to do the pull request

**Comment by kdere** [comment]
I just tried to do a pull request 60 for a file with minor editing.  It did not build and seems that the problems was in fetching the CHIANTI database.  Why this should happen now, I don't understand.  I just previously did a PR for the quickstart notebook and there was no problem

**Comment by kdere** [comment]
this is the end of the raw Travis log

$ mkdir -p $XUVTOP

$ curl -L http://www.chiantidatabase.org/download/CHIANTI_8.0.2_data.tar.gz | tar xz -C $XUVTOP
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  4  254M    4 12.3M    0     0  2345k      0  0:01:51  0:00:05  0:01:46 2529k
curl: (18) transfer closed with 253878598 bytes remaining to read

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by wtbarnes** [comment]
Closing. Seems like a lot of this has been taken care of. We can take care of commented out blocks of code as we find them and address any specific issues when they come up.
