### ISSUE TITLE
Allow ChiantiPy to be imported without having to install the database

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#88]
Most of the core classes import `tools.data` which automatically reads info from the database. That means anytime `import ChiantiPy.core` is called, the database has to be installed or an `IOError` is thrown. This is a problem primarily with Read the Docs as very often the download of the database fails or causes the build to timeout.

One alternative to this would be to just catch the exception and print a warning since no actual code needs to be run on RTD.

**Comment by kdere** [comment]
sounds like a good idea

**Comment by wtbarnes** [comment]
Solved by #94
