### ISSUE TITLE
Base class of `ioneq`

### ISSUE THREAD

**Issue by wtbarnes** [chianti-atomic/ChiantiPy#89]
Why does the `ioneq` object subclass `ion`? It doesn't seem to use or benefit from any of the methods or attributes of `ion`

**Comment by kdere** [comment]
the ion Class is used in ioneq to calculate an ionization equilibrium from the ionization rates.  Maybe it does not have to be subclassed if it already knows about ion.  This is something I am not sure of.

**Comment by wtbarnes** [comment]
Yes it is used in the ionization equilibrium calculation (in the `calculate` method) but I think it is a bit confusing to subclass the single `ion` class in an object that represents multiple ions.

**Comment by kdere** [comment]
how else could we do it -- to get the ionization and recombination rates?

**Comment by wtbarnes** [comment]
The `ion` object can still be called inside of `ioneq` without subclassing `ion`. I think actually everything would be exactly the same, just deleting `ion` in the class definition or replacing it  with object, e.g.

```Python
class ioneq:
```
or
```Python
class ioneq(object):
```

**Comment by kdere** [comment]
OK, I will give it a try (tomorrow).

**Comment by wtbarnes** [comment]
Fixed by #90
