### ISSUE TITLE
setting up ChiantiPy on Read the Docs

### ISSUE THREAD

**Issue by kdere** [chianti-atomic/ChiantiPy#9]
I now have an account on Read-the-Docs.  When I went to link to to the master copy of ChiantiPy on github, rtd said that there already was a ChiantiPy project there.  It looks like it is the example you (wtbarns) built.  Would it be OK to remove it?

**Comment by wtbarnes** [comment]
I suspected there might be a conflict between the two builds. I've removed mine so it should work now.

**Comment by kdere** [comment]
That worked and the docs how now been built

**Comment by wtbarnes** [comment]
Read The Docs has been implemented and built. I think this issue can be closed.

**Comment by kdere** [comment]
OK, I am closing the issue
